language: java
jdk:
 - openjdk11
before_install:
 - chmod +x gradlew
install:
 - mkdir $HOME/localrepo/
script:
 - ./gradlew -b browsermob-proxy/build.gradle build createPom uploadArchives -x checkstyleMain -x checkstyleTest -PlocalRepository=file:///$HOME/localrepo/ -PbuildNumber=$TRAVIS_BUILD_NUMBER
 - ./gradlew build release sonarqube createPom uploadArchives -PlocalRepository=file:///$HOME/localrepo/ -PbuildNumber=$TRAVIS_BUILD_NUMBER
branches:
  only:
  - master
notifications:
  email:
  - tkohegyi2@gmail.com
