# this starts from wilma base, so just adds the message search related things
FROM epam/wilma

MAINTAINER Tamas Kohegyi <tkohegyi2@gmail.com>

RUN \
  mkdir /data/wilma-ms && \
  mkdir /data/wilma/messages && \
  cd /data/wilma-ms && \
  apt-get update && \
  apt-get upgrade && \
  apt-get install -y openjdk-7-jdk && \
  rm -rf /var/libs/apt/lists/* && \
  wget https://github.com/epam/Wilma/releases/download/V1.1.73/wilma-message-search-1.1.73.zip && \
  unzip -o wilma-message-search-1.1.73.zip && \
  rm -f wilma-message-search-1.1.73.zip

COPY start_wilma_and_message_search.sh /data/
RUN \
  cd /data && \
  chmod 777 *.sh

WORKDIR /data

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

# you may start wilma and message search with default setting by /data/start_wilma_and_message_search.sh
CMD ["bash"]

# expose UI port and jmx port of message search
EXPOSE 9093 9010